version: "2"

volumes:
  grafana-storage:
    driver: local

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    user: "472"
    volumes:
      - grafana-storage:/var/lib/grafana