version: "2"

volumes:
  grafana-storage:
    driver: local
  grafana-config:
    driver: local

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:6.5.0-ubuntu
    ports:
      - 3000:3000
    user: "472"
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-config:/etc/grafana
