version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    container_name: 'rabbitmq'
    restart: always
    environment:
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=admin@rabbitmq.com
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - './data:/bitnami'
    networks:
      - app
networks:
  app:
    external: true